# Copyright (c) 2026 Quan-feng WU <wuquanfeng@ihep.ac.cn>
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

# ─── Precomputed massive Fermi-Dirac integrals (cf. https://github.com/Fenyutanchan/code-2507.12270) ───
# The integral table is generated by deps/build.jl at build time.

const _FD_integral_file = joinpath(integrals_directory, "integrals_massive_FD.csv")

@assert isfile(_FD_integral_file) "Precomputed integral file not found: $(_FD_integral_file). Please run `import Pkg; Pkg.build(\"HNL_BBN_Code\")` to generate it."

const _integral_data_FD = let
    raw = readdlm(_FD_integral_file, ','; comments=true, comment_char='#')
    (T_over_m = raw[:, 1], energy_density_FD = raw[:, 2])
end
const _Tₘ_min_FD = minimum(_integral_data_FD.T_over_m)
const _Tₘ_max_FD = maximum(_integral_data_FD.T_over_m)

const _log_ρ_FD_vs_log_Tₘ = LinearInterpolation(
    log.(_integral_data_FD.energy_density_FD),
    log.(_integral_data_FD.T_over_m);
    extrapolation=ExtrapolationType.Constant, cache_parameters=true
)

"""
    _numeric_energy_density_FD(Tₘ) -> Float64

Dimensionless energy density ρ/(m⁴) per internal degree of freedom
for a massive Fermi-Dirac species, as a function of Tₘ = T/m.
"""
function _numeric_energy_density_FD(Tₘ)
    if Tₘ < _Tₘ_min_FD
        return 0.0
    elseif Tₘ > _Tₘ_max_FD
        return (π^2 / 30) * (7 / 8) * Tₘ^4
    else
        return (exp ∘ _log_ρ_FD_vs_log_Tₘ ∘ log)(Tₘ)
    end
end

export ρ_ℓ, ρ_ν

# ─── Energy density of charged lepton ℓ_α ───

"""
    ρ_ℓ(α::Int, T::EnergyUnit) -> EnergyUnit (dim 4)

Energy density of charged lepton ℓ_α (particle + antiparticle) at temperature T.
Uses precomputed QuadGK integrals with log-log interpolation.

ρ_ℓ = g_ℓ × ρₘ(T/m_ℓ) × m_ℓ⁴

where g_ℓ = 4 (2 spin × particle/antiparticle).
"""
function ρ_ℓ(α::Int, T::EnergyUnit)
    Tₘ = T / m_ℓ[α] # T / m_ℓ
    @check_EU_dimension Tₘ 0 # dimensionless
    g_ℓ = 4.0  # 2 spin × 2 (particle + antiparticle)
    return g_ℓ * m_ℓ[α]^4 * _numeric_energy_density_FD(Tₘ)
end

# ─── Energy density of neutrino ν_α ───

"""
    ρ_ν(T::EnergyUnit) -> EnergyUnit (dim 4)

Energy density of a single neutrino species (ν_α + ν̄_α) at temperature T.
Massless approximation: ρ_ν = (7/8) × (2/g_total) × (π²/30) × T⁴

g_ν = 2 (left-handed ν + right-handed ν̄), so ρ_ν = 2 × (7/8) × (π²/30) × T⁴
"""
function ρ_ν(T::EnergyUnit)
    return 2T^4 * (7 / 8) * π^2 / 30
end
